using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AuthSimulator.Business.Utility
{
    /// <summary>
    /// Constants
    /// </summary>
    public sealed class Constants
    {

        private Constants()
        {
            
        }

        /// <summary>
        /// Token
        /// </summary>
        public const string TokenType = "Bearer";

        /// <summary>
        /// Authorization code
        /// </summary>

        public const string AuthorizationCode = "authorization_code";

        /// <summary>
        /// Size of autogenerated code
        /// </summary>

        public const int CodeSize = 72;
    }
}
