version: '3.4'
services:
    authsimulator:
        image: robydx/authsimulator
        restart: on-failure
        environment:
            - ConnectionStrings:Lite=litedata/authsimulator.db
            - ConnectionMode=Lite
        ports:
            - "6080:80" 
        volumes:
            - authdata:/app/litedata
volumes:
    authdata: