version: '3.4'
services:
    sqldata:
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        volumes:
            - mssql-server-data:/var/opt/mssql
        environment:
            - SA_PASSWORD=Auth1234@@
            - ACCEPT_EULA=Y
        ports:
            - "5434:1433"
    authsimulator:
        image: robydx/authsimulator
        restart: on-failure
        environment:
            - ConnectionStrings:SQL=Server=sqldata,1433;Database=AuthSimulator;User Id=sa;Password=Auth1234@@;MultipleActiveResultSets=True;App=EntityFramework
            - ConnectionMode=sql
        ports:
            - "6080:80" 
volumes:
    mssql-server-data: