name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file AuthSimulator/Dockerfile --tag authsimulator:latest
    - name: Tag
      run: docker tag authsimulator:latest robydx/authsimulator:latest
    - name: Push
      run: |
        docker push robydx/authsimulator:latest
