name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file AuthSimulator/Dockerfile --tag authsimulator
    - name: Tag
      run: |
        docker tag authsimulator robydx/authsimulator:${{ github.sha }}
        docker tag authsimulator robydx/authsimulator:latest
    - name: Push
      run: |
        docker push robydx/authsimulator:${{ github.sha }}
        docker push robydx/authsimulator:latest
