name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file AuthSimulator/Dockerfile --tag robydx/authsimulator:$(date +%s)
    - name: Tags
      run: |
        docker tag back robydx/authsimulator:${{ github.sha }}
        docker tag back robydx/authsimulator/back:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/back:latest   
